version: "3.8"
services:
  nginx:
    image: ghcr.io/planckproject/mind-care/nginx:latest
    ports:
      - "80:80"
      - "443:80"
    depends_on:
      - api
      - frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  api:
    image: ghcr.io/planckproject/mind-care/api:latest
    environment:
      - "GIN_MODE=release"
      - "MONGO_URI=${MONGO_URI}"
      - "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}"
      - "BING_MAPS_API_KEY=${BING_MAPS_API_KEY}"
  frontend:
    image: ghcr.io/planckproject/mind-care/frontend:latest
    environment:
      - "API_SERVER_URI=${API_SERVER_URI}"
